### ISSUE TITLE
Recurring events with time

### ISSUE THREAD

**Issue by aunderwo** [molawson/repeatable#8]
Is it possible to include a time with a repeating event e.g Every Monday from 10am to 3pm??

**Comment by molawson** [comment]
That's certainly possible.  I haven't thought much about how it could best be implemented since it hasn't been part of my use-case thus far. Can you give me a little more idea of the type of things you're looking for and how it might fit into the current structure of this library?

**Comment by molawson** [comment]
@aunderwo Since it's been a couple of months and I haven't heard anything back, I'm going to close this. Feel free to reopen it if you have any specific ideas.  Thanks!
